/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanaprincipal;

import conexiones.Con_RealizarConexion;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import dialogos.Dlg_Acciones;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author rufis
 */
public class Frm_IniciarSesion extends javax.swing.JFrame {
    
    private String servidor;
    private Integer puerto;
    private String usuario;
    private String contrasena;
    private Clip clip;
    
    /**
     * Creates new form Frm_Usuario
     */
    public Frm_IniciarSesion() {
        initComponents();
        
        this.setTitle("Conexión con Base de Datos, por Rufino Serrano");
        setIconImage(new ImageIcon(getClass().getResource("../images/woodman.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_iniciar_sesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txf_servidor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txf_usuario = new javax.swing.JTextField();
        pwf_contrasena = new javax.swing.JPasswordField();
        txf_puerto = new javax.swing.JTextField();
        img_woodman = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_iniciar_sesion.setText("Iniciar sesión");
        btn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_sesionActionPerformed(evt);
            }
        });

        jLabel1.setText("Dirección del servidor:");

        txf_servidor.setText("localhost");

        jLabel2.setText("Puerto:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Bienvenido al programa de Bases de Datos realizado por Rufino Serrano.");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Inicie sesión en su gestor de Bases de Datos para continuar.");

        jLabel5.setText("Contraseña:");

        jLabel6.setText("Usuario:");

        txf_usuario.setText("root");
        txf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_usuarioActionPerformed(evt);
            }
        });

        pwf_contrasena.setText("toor");

        txf_puerto.setText("3306");
        txf_puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_puertoActionPerformed(evt);
            }
        });

        img_woodman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woodman.png"))); // NOI18N
        img_woodman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_woodmanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_woodmanMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img_woodmanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_iniciar_sesion)
                                .addGap(196, 196, 196)))
                        .addComponent(img_woodman)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txf_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btn_iniciar_sesion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(img_woodman)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_puertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_puertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_puertoActionPerformed

    private void btn_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionActionPerformed
        // TODO add your handling code here:
        //direccionDB= "jdbc:mysql://localhost:3306/" + txf_base_de_datos.getText() + "?useSSL=false";
        Connection con= null;
        if (txf_usuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error: el campo de 'usuario' no puede quedarse vacío.", "Error al iniciar sesión", 2);
        } else {
            servidor= txf_servidor.getText();
            puerto= Integer.parseInt(txf_puerto.getText());
            usuario= txf_usuario.getText();
            contrasena= pwf_contrasena.getText();
            
            try {
                Con_RealizarConexion rc= new Con_RealizarConexion();
                con= rc.hazConexionNoBBDD(servidor, puerto, usuario, contrasena);
                
                if (clip != null) {
                    clip.stop();
                }

                JOptionPane.showMessageDialog(null, "Datos correctos. Bienvenido.", "Inicio de sesión correcto", 1);

                Dlg_Acciones ccbd= new Dlg_Acciones(this, true);
                ccbd.setVisible(true);
            } catch (SQLException ex) {
                if (ex.getErrorCode() == 0) {
                    JOptionPane.showMessageDialog(null, "Error: no se ha encontrado el servidor '" + servidor + "' o no se ha podido conectar a través del puerto '" + puerto + "'.", "Error al conectarse al servidor", 2);
                }
                if (ex.getErrorCode() == 1045) {
                    JOptionPane.showMessageDialog(null, "Error: el usuario '" + usuario + "' no existe o la contraseña introducida no coincide con los datos.", "Error al iniciar sesión", 2);
                }
                if (ex.getErrorCode() == 1130) {
                    JOptionPane.showMessageDialog(null, "Error: el servidor '" + servidor + "' ha rechazado la conexión." + "\n" +
                        "Considere comprobar si el usuario '" + usuario +"' tiene acceso a este servidor de Bases de Datos.", "Error al conectarse al servidor", 2);
                }
            } finally {
                try {
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }

            }    
    }//GEN-LAST:event_btn_iniciar_sesionActionPerformed

    private void img_woodmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_woodmanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_img_woodmanMouseClicked

    private void img_woodmanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_woodmanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_img_woodmanMouseEntered

    private void img_woodmanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_woodmanMousePressed
        // TODO add your handling code here:
        int respuesta= JOptionPane.showConfirmDialog(null, "¿Desea escuchar Mega Man 2 - Wood Man Stage (Sega Genesis Remix)?" + "\n" +
            "Podrá salir del programa aunque el audio comience a sonar.", "Reproducción de audio", JOptionPane.YES_NO_OPTION, 3);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                if (clip != null) {
                    clip.stop();
                }
                
                File wood= new File("src/audio/woodman.wav");
                
                clip= AudioSystem.getClip();
                clip.open(AudioSystem.getAudioInputStream(wood));
                clip.start();

                //Thread.sleep(clip.getMicrosecondLength()/1000);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_img_woodmanMousePressed

    private void txf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_usuarioActionPerformed

    public String getServidor() {
        return servidor;
    }

    public void setServidor(String servidor) {
        this.servidor = servidor;
    }
    
    public Integer getPuerto() {
        return puerto;
    }

    public void setPuerto(Integer puerto) {
        this.puerto = puerto;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasena() {
        return contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar_sesion;
    private javax.swing.JLabel img_woodman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwf_contrasena;
    private javax.swing.JTextField txf_puerto;
    private javax.swing.JTextField txf_servidor;
    private javax.swing.JTextField txf_usuario;
    // End of variables declaration//GEN-END:variables
}
