package dialogos;

import conexiones.Con_RealizarConexion;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import ventanaprincipal.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rufis
 */
public class Dlg_CrearBaseDeDatos extends javax.swing.JDialog {
    
    private String servidor;
    private Integer puerto;
    private String usuario;
    private String contrasena;
    private String baseDeDatos;
    private String codificacionCaracteres;
    private String intercalacionCaracteres;
    private Dlg_Acciones padreConectarCrear= null;
    private Dlg_CrearBaseDeDatos padreCrear= null;

    /**
     * Creates new form Dlg_CrearBaseDatos
     */
    public Dlg_CrearBaseDeDatos(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        if (parent instanceof Dlg_Acciones) {
            padreConectarCrear= (Dlg_Acciones)parent;
        }
        
        if (parent instanceof Dlg_CrearBaseDeDatos) {
            padreCrear= (Dlg_CrearBaseDeDatos)parent;
        }
        
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                cerrarDialogo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_crear_nueva_base_de_datos = new javax.swing.JButton();
        txf_int_cals = new javax.swing.JTextField();
        txf_cod_cars = new javax.swing.JTextField();
        txf_nombre_base_de_datos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Codificación de caracteres:");

        jLabel3.setText("Intercalación de caracteres:");

        btn_crear_nueva_base_de_datos.setText("Crear nueva Base de Datos");
        btn_crear_nueva_base_de_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_nueva_base_de_datosActionPerformed(evt);
            }
        });

        txf_int_cals.setEditable(false);
        txf_int_cals.setText("utf8_spanish2_ci");

        txf_cod_cars.setEditable(false);
        txf_cod_cars.setText("utf8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_cod_cars, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_int_cals, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_nombre_base_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btn_crear_nueva_base_de_datos)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_nombre_base_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txf_cod_cars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txf_int_cals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btn_crear_nueva_base_de_datos)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crear_nueva_base_de_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_nueva_base_de_datosActionPerformed
        // TODO add your handling code here:
        Connection con= null;
        
        baseDeDatos= txf_nombre_base_de_datos.getText();
        codificacionCaracteres= txf_cod_cars.getText();
        intercalacionCaracteres= txf_int_cals.getText();
        
        servidor= Main.getIs().getServidor();
        puerto= Main.getIs().getPuerto();
        usuario= Main.getIs().getUsuario();
        contrasena= Main.getIs().getContrasena();
        
        try {
            Con_RealizarConexion rc= new Con_RealizarConexion();
            con= rc.hazConexionNoBBDD(servidor, puerto, usuario, contrasena);

            Statement st = con.createStatement();

            // Creación de la tabla:
            st.executeUpdate(
                "create database " + baseDeDatos +
                " default character set " + codificacionCaracteres +
                " collate " + intercalacionCaracteres);
            
            int respuesta = JOptionPane.showConfirmDialog(null, "Base de datos '" + baseDeDatos + "' creada correctamente." + "\n" +
                "¿Desea operar con ella ahora?", "Operación realizada exitosamente", JOptionPane.YES_NO_OPTION, 3);
                if (respuesta == JOptionPane.YES_OPTION) {               
                    this.setVisible(false);
                    this.dispose();
            
                    Dlg_OperarBaseDeDatos obd= new Dlg_OperarBaseDeDatos(this, true);
                    obd.setVisible(true);
                }
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 1007) {
                JOptionPane.showMessageDialog(null, "Error: la base de datos '" + baseDeDatos + "' ya existe.", "Error al crear la base de datos", 2);
            }
            if (ex.getErrorCode() == 1102) {
                JOptionPane.showMessageDialog(null, "Error: el nombre introducido es demasiado largo.", "Error al crear la base de datos", 2);
            }
            if (ex.getErrorCode() == 1064) {
                JOptionPane.showMessageDialog(null, "Error: el nombre introducido no es válido.", "Error al crear la base de datos", 2);
            }
        }
    }//GEN-LAST:event_btn_crear_nueva_base_de_datosActionPerformed

    public void setNombreBaseDatos (String nombreBaseDatosEntra) {
        txf_nombre_base_de_datos.setText(nombreBaseDatosEntra);
    }
    
    public void cerrarDialogo() {
        this.setVisible(false);
        this.dispose();
        
        if (padreConectarCrear != null) {
            padreConectarCrear.setVisible(true);
        }
        
        if (padreCrear != null) {
            padreCrear.setVisible(true);
        }
        
    }

    public String getBaseDeDatos() {
        return baseDeDatos;
    }

    public void setBaseDeDatos(String baseDeDatos) {
        this.baseDeDatos = baseDeDatos;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dlg_CrearBaseDeDatos dialog = new Dlg_CrearBaseDeDatos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crear_nueva_base_de_datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txf_cod_cars;
    private javax.swing.JTextField txf_int_cals;
    private javax.swing.JTextField txf_nombre_base_de_datos;
    // End of variables declaration//GEN-END:variables
}
