/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogos;

import conexiones.Con_RealizarConexion;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ventanaprincipal.Main;

/**
 *
 * @author rufis
 */
public class Dlg_ConectarBaseDeDatos extends javax.swing.JDialog {
    
    private String servidor;
    private Integer puerto;
    private String baseDeDatos;
    private String usuario;
    private String contrasena;
    private Dlg_Acciones miPadre;
    private ArrayList<String> listaBasesDeDatos;
    private DefaultComboBoxModel modeloBasesDeDatos= new DefaultComboBoxModel();

    /**
     * Creates new form Dlg_ConectarBaseDeDatos
     */
    public Dlg_ConectarBaseDeDatos(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        miPadre= (Dlg_Acciones)parent;
        
        generarListaBasesDeDatos();
        
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                cerrarDialogo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_operar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcb_bases_de_datos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_operar.setText("Operar con base de datos");
        btn_operar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jcb_bases_de_datos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcb_bases_de_datos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcb_bases_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_operar)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcb_bases_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_operar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_operarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operarActionPerformed
        // TODO add your handling code here:
        Connection con= null;
        
        servidor= Main.getIs().getServidor();
        puerto= Main.getIs().getPuerto();
        baseDeDatos= (String)jcb_bases_de_datos.getSelectedItem();
        usuario= Main.getIs().getUsuario();
        contrasena= Main.getIs().getContrasena();
        
        try {
            Con_RealizarConexion rc= new Con_RealizarConexion();
            con= rc.hazConexionBBDD(servidor, puerto, baseDeDatos, usuario, contrasena);
            
            JOptionPane.showMessageDialog(null, "Base de Datos encontrada. Accediendo a la Base de Datos.");
            
            this.setVisible(false);
            this.dispose();
            
            Dlg_OperarBaseDeDatos obd= new Dlg_OperarBaseDeDatos(this, true);
            obd.setVisible(true);
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 1044) {
                JOptionPane.showMessageDialog(null, "Error: el usuario '" + usuario + "' no tiene acceso a la Base de Datos '" + baseDeDatos + "' .", "Error al acceder a la base de datos", 2);
            }
//            if (ex.getErrorCode() == 1049) {
//                int respuesta = JOptionPane.showConfirmDialog(null, "Error: la base de datos '" + baseDeDatos + "' no existe. ¿Desea crearla?", "Error al encontrar la Base de Datos", JOptionPane.YES_NO_OPTION, 3);
//                if (respuesta == JOptionPane.YES_OPTION) {               
//                    Dlg_CrearBaseDeDatos cbd= new Dlg_CrearBaseDeDatos(this, true);
//                    cbd.setNombreBaseDatos((String)jcb_bases_de_datos.getSelectedItem());
//                    cbd.setVisible(true);
//                    
//                    this.setVisible(false);
//                    this.dispose();
//                }
//            }
        }
    }//GEN-LAST:event_btn_operarActionPerformed
  
    public void cerrarDialogo() {
        this.setVisible(false);
        this.dispose();
        
        miPadre.setVisible(true);
    }
    
    public void generarListaBasesDeDatos() {   
        Connection con= null;
        
        servidor= Main.getIs().getServidor();
        puerto= Main.getIs().getPuerto();
        usuario= Main.getIs().getUsuario();
        contrasena= Main.getIs().getContrasena();
        
        listaBasesDeDatos= new ArrayList();
        
        try {
            Con_RealizarConexion rc= new Con_RealizarConexion();
            con= rc.hazConexionNoBBDD(servidor, puerto, usuario, contrasena);
            
            listaBasesDeDatos= rc.listaBases(con);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        crearModelo();
        
        jcb_bases_de_datos.setModel(modeloBasesDeDatos);
    }
    
    public void crearModelo() {
        for (int i = 0; i < listaBasesDeDatos.size(); i++) {
            modeloBasesDeDatos.addElement(listaBasesDeDatos.get(i));
        }
    }

    public String getBaseDeDatos() {
        return baseDeDatos;
    }

    public void setBaseDeDatos(String baseDeDatos) {
        this.baseDeDatos = baseDeDatos;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_ConectarBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_ConectarBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_ConectarBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_ConectarBaseDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dlg_ConectarBaseDeDatos dialog = new Dlg_ConectarBaseDeDatos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_operar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcb_bases_de_datos;
    // End of variables declaration//GEN-END:variables
}
