package dialogos.operaciones;

import conexiones.Con_RealizarConexion;
import dialogos.Dlg_Acciones;
import dialogos.Dlg_OperarBaseDeDatos;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import tablas.Tabla;
import ventanaprincipal.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rufis
 */
public class Dlg_CrearTabla extends javax.swing.JDialog {

    private String servidor;
    private Integer puerto;
    private String baseDeDatos;
    private String tabla;
    private String usuario;
    private String contrasena;
    private String tipoCampo;
    private Dlg_OperarBaseDeDatos miPadre;
    private DefaultListModel dlmCampos;

    /**
     * Creates new form Dlg_CrearBaseDatos
     */
    public Dlg_CrearTabla(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        miPadre = (Dlg_OperarBaseDeDatos)parent;
        
        dlmCampos= new DefaultListModel();
        lst_campos.setModel(dlmCampos);
        
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                cerrarDialogo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_crear_tabla = new javax.swing.JButton();
        txf_nombre_tabla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_campos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txf_nombre_campo = new javax.swing.JTextField();
        jcb_tipo_campo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ckb_pk = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txf_valor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ckb_null = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        ckb_ai = new javax.swing.JCheckBox();
        spn_longitud = new javax.swing.JSpinner();
        btn_anadir_campo = new javax.swing.JButton();
        btn_eliminar_campo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_crear_tabla.setText("Crear nueva tabla");
        btn_crear_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_tablaActionPerformed(evt);
            }
        });

        txf_nombre_tabla.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Lista de campos");

        lst_campos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_camposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lst_campos);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setText("Añade un campo:");

        jLabel4.setText("Nombre:");

        jcb_tipo_campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un tipo", "INT", "FLOAT", "DOUBLE", "DECIMAL", "VARCHAR", "CHAR", "BINARY" }));
        jcb_tipo_campo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_tipo_campoItemStateChanged(evt);
            }
        });
        jcb_tipo_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipo_campoActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo:");

        jLabel6.setText("Longitud:");

        ckb_pk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_pkActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor predeterminado:");

        jLabel12.setText("Clave primaria:");

        jLabel13.setText("Campos no nulos:");

        ckb_null.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_nullActionPerformed(evt);
            }
        });

        jLabel15.setText("Auto-incremental:");

        ckb_ai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_aiActionPerformed(evt);
            }
        });

        btn_anadir_campo.setText("Añadir registro");
        btn_anadir_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadir_campoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txf_valor)
                    .addComponent(spn_longitud)
                    .addComponent(jcb_tipo_campo, 0, 240, Short.MAX_VALUE)
                    .addComponent(txf_nombre_campo))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(144, 144, 144))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_anadir_campo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckb_null)
                            .addComponent(ckb_pk)
                            .addComponent(ckb_ai))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_nombre_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_tipo_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spn_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ckb_pk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(ckb_null))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(ckb_ai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_anadir_campo)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btn_eliminar_campo.setText("Eliminar campo seleccionado");
        btn_eliminar_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_campoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txf_nombre_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btn_crear_tabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminar_campo)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txf_nombre_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear_tabla)
                    .addComponent(btn_eliminar_campo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crear_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_tablaActionPerformed
        // TODO add your handling code here:
            Connection con= null;
            servidor= Main.getIs().getServidor();
            puerto= Main.getIs().getPuerto();
            baseDeDatos= miPadre.getBaseDeDatos();
            usuario= Main.getIs().getUsuario();
            contrasena= Main.getIs().getContrasena();
            tabla= txf_nombre_tabla.getText();
            
            String listaCampos= "";

            try {
                Con_RealizarConexion rc= new Con_RealizarConexion();
                con= rc.hazConexionBBDD(servidor, puerto, baseDeDatos, usuario, contrasena);
                Statement st = con.createStatement();
                
                for (int i = 0; i < dlmCampos.size(); i++) {
                    if (i == dlmCampos.size()-1) {
                        listaCampos= listaCampos + dlmCampos.getElementAt(i);
                    } else {
                        listaCampos= listaCampos + dlmCampos.getElementAt(i) + ", ";
                    }
                    
                }
                
                // Creación de la tabla:
                st.executeUpdate(
                    "create table `" + baseDeDatos + "`.`" + tabla + "` " +
                    "(" + listaCampos + ");");


                // Inserción de valores:
    //            String nombres[]= {"Juan", "Pedro", "Antonio"};
    //            String direcciones[]= {"C/ Falsa 123", "C/ Algo 44", "C/ Cristiano Ronaldo Suuuuuuu"};
    //            String telefonos[]= {"123", "456", "789"};
    //
    //            for (int i= 0; i < nombres.length; i++) {
    //                st.executeUpdate(
    //                    "insert into contacto (nombre, direccion, telefono) values " +
    //                    "('"+nombres[i]+"', '"+direcciones[i]+"', '"+telefonos[i]+"')");
    //            }
            } catch (SQLException ex) {
                if (ex.getErrorCode() == 1050) {
                    JOptionPane.showMessageDialog(null, "Error: la tabla '" + tabla + "' ya existe." + "\n" +
                        "Considere elegir otro nombre.", "Error al crear la tabla", 2);
                }
                if (ex.getErrorCode() == 1064) {
                    JOptionPane.showMessageDialog(null, "Error: ha ocurrido un error de sintaxis." + "\n" + 
                       "Considere comprobar los campos almacenados.", "Error de sintaxis", 2);
                    System.out.println("create table `" + baseDeDatos + "`.`" + tabla + "` " +
                    "(" + listaCampos + ");");
                }
                if (ex.getErrorCode() == 1067) {
                    JOptionPane.showMessageDialog(null, "Error: uno o más campos tienen un valor por defecto no válido." + "\n" + 
                       "Considere comprobar los campos almacenados.", "Error de sintaxis", 2);
                }
                System.out.println(ex.getMessage() + ", " + ex.getErrorCode());
            }
        
    }//GEN-LAST:event_btn_crear_tablaActionPerformed

    private void jcb_tipo_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipo_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipo_campoActionPerformed

    private void ckb_pkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_pkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_pkActionPerformed

    private void ckb_nullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_nullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_nullActionPerformed

    private void ckb_aiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_aiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckb_aiActionPerformed

    private void jcb_tipo_campoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_tipo_campoItemStateChanged
        // TODO add your handling code here:
        tipoCampo= (String)jcb_tipo_campo.getSelectedItem();
        switch (tipoCampo) {
            case "INT":
                spn_longitud.setEnabled(false);
                txf_valor.setText("0");
                break;
            case "FLOAT":
                spn_longitud.setEnabled(false);
                txf_valor.setText("0");
                break;
            case "DOUBLE":
                spn_longitud.setEnabled(false);
                txf_valor.setText("0");
                break;
            case "DECIMAL":
                spn_longitud.setEnabled(true);
                txf_valor.setText("0");
                break;
            case "VARCHAR":
                spn_longitud.setEnabled(true);
                txf_valor.setText("NULL");
                break;
            case "CHAR":
                spn_longitud.setEnabled(false);
                txf_valor.setText("NULL");
                break;
            case "BINARY":
                spn_longitud.setEnabled(true);
                txf_valor.setText("0");
                break;
        }
    }//GEN-LAST:event_jcb_tipo_campoItemStateChanged

    private void btn_anadir_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadir_campoActionPerformed
        // TODO add your handling code here:
        String nombre= txf_nombre_campo.getText();
        String tipo= (String)jcb_tipo_campo.getSelectedItem();
        Integer longitud= (Integer)spn_longitud.getValue();
        String valor= txf_valor.getText();
        boolean pk, notnull, ai;
        
        Tabla tb;
        
        if (jcb_tipo_campo.getSelectedItem().equals("Elige un tipo")) {
            System.out.println("no implementado");
        } else {
            tb= null;
            
            if (ckb_pk.isSelected() == true) {
                pk= true;
            } else {
                pk= false;
            }
            if (ckb_null.isSelected() == true) {
                notnull= true;
            } else {
                notnull= false;
            }
            if (ckb_ai.isSelected() == true) {
                ai= true;
            } else {
                ai= false;
            }
            
            if (tipo.equals("INT")) {
                longitud= 11;
                tb= new Tabla(nombre, tipo, valor, pk, notnull, ai);
            }
            //tb= new Tabla(nombre, tipo, longitud, valor, pk, notnull, ai);
            dlmCampos.addElement(tb);
        }
    }//GEN-LAST:event_btn_anadir_campoActionPerformed

    private void btn_eliminar_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_campoActionPerformed
        // TODO add your handling code here:
        dlmCampos.removeElementAt(lst_campos.getSelectedIndex());
    }//GEN-LAST:event_btn_eliminar_campoActionPerformed

    private void lst_camposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_camposMouseClicked
        // TODO add your handling code here:
        Tabla tb= (Tabla)dlmCampos.getElementAt(lst_campos.getSelectedIndex());
        txf_nombre_campo.setText(tb.getNombre());
        jcb_tipo_campo.setSelectedItem(tb.getTipo());
        if (tb.getLongitud() != null) {
            spn_longitud.setValue(tb.getLongitud());
        }
        txf_valor.setText(tb.getValor());
        if (tb.isPk() == true) {
            ckb_pk.setSelected(true);
        } else {
            ckb_pk.setSelected(false);
        }
        if (tb.isNotnull() == true) {
            ckb_null.setSelected(true);
        } else {
            ckb_null.setSelected(false);
        }
        if (tb.isAi() == true) {
            ckb_ai.setSelected(true);
        } else {
            ckb_ai.setSelected(false);
        }
    }//GEN-LAST:event_lst_camposMouseClicked

    public void setNombreBaseDatos (String nombreBaseDatosEntra) {
        txf_nombre_tabla.setText(nombreBaseDatosEntra);
    }
    
    public void cerrarDialogo() {
        this.setVisible(false);
        this.dispose();
        miPadre.setVisible(true);
    }

    public String getBaseDeDatos() {
        return baseDeDatos;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_CrearTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dlg_CrearTabla dialog = new Dlg_CrearTabla(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadir_campo;
    private javax.swing.JButton btn_crear_tabla;
    private javax.swing.JButton btn_eliminar_campo;
    private javax.swing.JCheckBox ckb_ai;
    private javax.swing.JCheckBox ckb_null;
    private javax.swing.JCheckBox ckb_pk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_tipo_campo;
    private javax.swing.JList<String> lst_campos;
    private javax.swing.JSpinner spn_longitud;
    private javax.swing.JTextField txf_nombre_campo;
    private javax.swing.JTextField txf_nombre_tabla;
    private javax.swing.JTextField txf_valor;
    // End of variables declaration//GEN-END:variables
}
